management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      repositories:
        enabled: false
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false