server:
  port: 8080
spring:
  datasource:
    #数据库文件存放 /doc/sql目录下
    url: jdbc:mysql://ip:3306/merchant_pay?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useOldAliasMetadataBehavior=true
    username: root
    password: 123456.qq
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: ip
    password: 123456.qq